#pragma once
#include <array>
#include <string_view>
namespace sourcerune::state::ids {
struct Entry { std::string_view id; std::string_view group; };
inline constexpr std::array<Entry, 64> kPublicParameters {{
    Entry{"sourceCharacter", "SOURCE"},
    Entry{"badSignal", "TRANSMISSION"},
    Entry{"dropout", "TRANSMISSION"},
    Entry{"interference", "TRANSMISSION"},
    Entry{"codecDamage", "TRANSMISSION"},
    Entry{"bandwidthLoss", "TRANSMISSION"},
    Entry{"noiseStatic", "TRANSMISSION"},
    Entry{"bitrateArtifacts", "TRANSMISSION"},
    Entry{"signalCompression", "TRANSMISSION"},
    Entry{"conditionMode", "CONDITION"},
    Entry{"condition", "CONDITION"},
    Entry{"rattle", "CONDITION"},
    Entry{"buzz", "CONDITION"},
    Entry{"deviceCompression", "CONDITION"},
    Entry{"instability", "CONDITION"},
    Entry{"imbalance", "CONDITION"},
    Entry{"wowFlutter", "CONDITION"},
    Entry{"intermittentContact", "CONDITION"},
    Entry{"coverAmount", "WALL_COVER"},
    Entry{"coverLeak", "WALL_COVER"},
    Entry{"coverResonance", "WALL_COVER"},
    Entry{"motionMode", "MOTION"},
    Entry{"startDistance", "MOTION"},
    Entry{"closestDistance", "MOTION"},
    Entry{"endDistance", "MOTION"},
    Entry{"motion", "MOTION"},
    Entry{"speed", "MOTION"},
    Entry{"doppler", "MOTION"},
    Entry{"width", "MOTION"},
    Entry{"perspective", "MOTION"},
    Entry{"spaceAmount", "SPACE_ENVIRONMENT"},
    Entry{"spaceDecay", "SPACE_ENVIRONMENT"},
    Entry{"spaceCharacter", "SPACE_ENVIRONMENT"},
    Entry{"direct", "SPACE_ENVIRONMENT"},
    Entry{"early", "SPACE_ENVIRONMENT"},
    Entry{"tail", "SPACE_ENVIRONMENT"},
    Entry{"ambienceType", "AMBIENCE"},
    Entry{"ambience", "AMBIENCE"},
    Entry{"ambienceLevel", "AMBIENCE"},
    Entry{"ambienceDuck", "AMBIENCE"},
    Entry{"intelligibilityMode", "INTELLIGIBILITY"},
    Entry{"intelligibility", "INTELLIGIBILITY"},
    Entry{"hpf", "EQ_TONE"},
    Entry{"lpf", "EQ_TONE"},
    Entry{"b1Freq", "EQ_TONE"},
    Entry{"b1Gain", "EQ_TONE"},
    Entry{"b1Q", "EQ_TONE"},
    Entry{"b2Freq", "EQ_TONE"},
    Entry{"b2Gain", "EQ_TONE"},
    Entry{"b2Q", "EQ_TONE"},
    Entry{"b3Freq", "EQ_TONE"},
    Entry{"b3Gain", "EQ_TONE"},
    Entry{"b3Q", "EQ_TONE"},
    // Deprecated IDs stay reserved so public-array indices/host state never shift.
    // These three are LEGACY ONLY: no active UI schema, no fourth DSP filter.
    Entry{"b4Freq", "EQ_TONE"},
    Entry{"b4Gain", "EQ_TONE"},
    Entry{"b4Q", "EQ_TONE"},
    Entry{"finalTone", "EQ_TONE"},
    Entry{"inputGain", "MIX"},
    Entry{"mix", "MIX"},
    Entry{"outputGain", "MIX"},
    Entry{"feedback", "FEEDBACK"},
    Entry{"feedbackTone", "FEEDBACK"},
    Entry{"generatorType", "GENERATORS"},
    Entry{"generatorLevel", "GENERATORS"}
}};
inline constexpr std::array<std::string_view, 4> kStableSelectorIds {{ "sourceModel", "transmissionModel", "wallCoverModel", "spaceEnvironmentModel" }};
inline constexpr std::array<std::string_view, 6> kGlobalStateIds {{ "globalBypass", "uiLayout", "scenePreset", "deterministicSeed", "sync", "generatorOn" }};
} // namespace sourcerune::state::ids
